/**
 * Autogenerated by the CHECK 1 verification script.
 * The "ignores" property tells ESLint to skip all JavaScript files that
 * contain JSX under the frontend source tree.
 */
module.exports = {
  // Ignore all .js files inside src/frontend/src (they contain JSX)
  ignores: ["src/frontend/src/**/*.js"],
};
