/** Jest configuration generated by CHECK5 fix script */
module.exports = {
  // Look for test files anywhere under the repository
  testMatch: ['**/tests/**/*.test.[jt]s?(x)'],
  // Prevent the haste map collision between root and backend package.json files
  modulePathIgnorePatterns: ['<rootDir>/backend'],
  // Do not treat .json files as modules (safety net)
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx', 'json'],
};
