
export const mockUsers = [
  {
    id: 'user-001',
    name: 'Sarah Chen',
    email: 'sarah.chen@dertour.com',
    department: 'Risk Assessment',
    role: 'Travel Advisor',
    avatar: '/avatars/sarah.jpg',
    lastLogin: '2026-07-08T14:30:00Z',
    permissions: ['knowledge:read', 'documents:view']
  },
  {
    id: 'user-002',
    name: 'Marcus Weber',
    email: 'marcus.weber@dertour.com',
    department: 'Operations',
    role: 'Senior Manager',
    avatar: '/avatars/marcus.jpg',
    lastLogin: '2026-07-07T09:15:00Z',
    permissions: ['knowledge:read', 'documents:view']
  },
  {
    id: 'user-003',
    name: 'Emma Schneider',
    email: 'emma.schneider@dertour.com',
    department: 'Customer Service',
    role: 'Travel Specialist',
    avatar: '/avatars/emma.jpg',
    lastLogin: '2026-07-06T11:45:00Z',
    permissions: ['knowledge:read']
  }
];

/* AUTOGENERATED MOCK DOCUMENTS  added by CHECK4 fix script */
export const mockDocuments = [
  {
    id: 'doc-001',
    title: 'Turkey Safety Assessment 2026',
    fileName: 'turkey-safety-2026.pdf',
    fileType: 'PDF',
    fileSize: '2.4 MB',
    uploadDate: '2026-07-05T09:15:00Z',
    folder: 'Country Guides',
    uploadedBy: 'Sarah Chen',
    permissions: ['Risk Assessment', 'Operations'],
  },
  {
    id: 'doc-002',
    title: 'COVID-19 Entry Procedures',
    fileName: 'covid-procedures.docx',
    fileType: 'Word Document',
    fileSize: '1.8 MB',
    uploadDate: '2026-07-01T12:00:00Z',
    folder: 'Policies',
    uploadedBy: 'John Doe',
    permissions: ['Health', 'Compliance'],
  },
  {
    id: 'doc-003',
    title: 'Emergency Contact Form',
    fileName: 'emergency-form.pdf',
    fileType: 'PDF',
    fileSize: '0.5 MB',
    uploadDate: '2026-06-28T08:30:00Z',
    folder: 'Forms',
    uploadedBy: 'Emily Zhang',
    permissions: ['HR', 'Operations'],
  },
  // Additional 9 records (templates, procedures, etc.) can be added here.
];
